name: Build APK

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use macos-latest if you prefer
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the version you want to use, Android typically uses JDK 11

    - name: Set up Android SDK
      uses: react-native-community/setup-android@v2
      with:
        android-sdk-version: '35'  # Set to your required SDK version
    
    - name: Build APK
      run: ./gradlew assembleRelease  # This will build the release APK

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Adjust the path according to your project structure
